version: '3.3'

services:
   db:
     image: mysql:8.0.40-bookworm
     ports:
       - "3306:3306"
     volumes:
       - $HOME/db_data:/var/lib/mysql
       - $HOME/conf_mysql:/etc/my.cnf
     restart: unless-stopped
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8080:80"
     volumes:
       - $HOME/wordpress_files:/var/www/html
     restart: unless-stopped
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress
   
   phpmyadmin:
     depends_on:
       - db
     image: phpmyadmin/phpmyadmin
     ports:
       - "8181:80"
     restart: unless-stopped
     environment:
       MYSQL_USERNAME: root
       MYSQL_ROOT_PASSWORD: somewordpress
       PMA_HOST: db
     
